# Generated by Django 5.0.6 on 2024-07-17 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='burger',
            options={'ordering': ['nombre'], 'verbose_name': 'Burger', 'verbose_name_plural': 'Burgers'},
        ),
        migrations.AlterModelOptions(
            name='empanadas',
            options={'ordering': ['nombre'], 'verbose_name': 'Empanada', 'verbose_name_plural': 'Empanadas'},
        ),
        migrations.AlterModelOptions(
            name='entradas',
            options={'ordering': ['nombre'], 'verbose_name': 'Entrada', 'verbose_name_plural': 'Entradas'},
        ),
        migrations.AlterModelOptions(
            name='pizza',
            options={'ordering': ['nombre'], 'verbose_name': 'Pizzas', 'verbose_name_plural': 'Pizzas'},
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='avatares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
